version: '3.8'

# Development với volume mount (hot reload)
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://192.168.1.135:9009
      - NEXT_PUBLIC_FRONTEND_URL=http://192.168.1.135:9009
    command: npm run dev
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "5008:5008"
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5008
      - CORS_ORIGINS=http://localhost:3000,http://192.168.1.135:9009
    command: python app.py
    networks:
      - app-network
    healthcheck:
      disable: true

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./deploy/nginx.ip-mapping.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9009:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
