version: '3.8'

services:
  # Frontend (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  # Backend (Flask)
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend/instance:/app/instance
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
