version: '3.8'

# HTTP-only configuration for event.expsolution.io
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://event.expsolution.io
      - NEXT_PUBLIC_FRONTEND_URL=http://event.expsolution.io
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm run build && npm start"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5008
      - CORS_ORIGINS=http://event.expsolution.io,http://www.event.expsolution.io
    ports:
      - "5008:5008"
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    command: python app.py
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./deploy/nginx-event-only.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
