version: '3.8'

# Simple production setup with IP access
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://27.72.246.67:5008
      - NEXT_PUBLIC_FRONTEND_URL=http://27.72.246.67:3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5008
      - CORS_ORIGINS=http://27.72.246.67:3000,http://27.72.246.67:9009
    ports:
      - "5008:5008"
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    command: python app.py
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./deploy/nginx-simple.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
