version: '3.8'

# Production SSL configuration with domain
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./deploy/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=https://event.expsolution.io/api
      - NEXT_PUBLIC_FRONTEND_URL=https://event.expsolution.io
    restart: unless-stopped

  backend:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - CORS_ORIGINS=https://event.expsolution.io,https://www.event.expsolution.io
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

