"""init schema v1

Revision ID: 0b7055c4e4ce
Revises: 
Create Date: 2025-09-30 05:00:24.997485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7055c4e4ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('agenda_md', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('brand_logo_url', sa.String(length=1024), nullable=True),
    sa.Column('brand_primary_color', sa.String(length=7), nullable=True),
    sa.Column('brand_accent_color', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_start_datetime'), 'events', ['start_datetime'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.String(length=128), nullable=True),
    sa.Column('invitation_id', sa.String(length=128), nullable=True),
    sa.Column('qr_token', sa.String(length=128), nullable=True),
    sa.Column('group_tag', sa.String(length=50), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('rsvp_status', sa.String(length=20), nullable=True),
    sa.Column('checkin_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('email_subject_last', sa.String(length=255), nullable=True),
    sa.Column('attach_file_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', 'event_id', name='uq_guests_invitation_event')
    )
    op.create_index(op.f('ix_guests_checkin_at'), 'guests', ['checkin_at'], unique=False)
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=True)
    op.create_index(op.f('ix_guests_event_id'), 'guests', ['event_id'], unique=False)
    op.create_index(op.f('ix_guests_full_name'), 'guests', ['full_name'], unique=False)
    op.create_index(op.f('ix_guests_group_tag'), 'guests', ['group_tag'], unique=False)
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_index(op.f('ix_guests_invitation_id'), 'guests', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_guests_is_vip'), 'guests', ['is_vip'], unique=False)
    op.create_index(op.f('ix_guests_organization'), 'guests', ['organization'], unique=False)
    op.create_index(op.f('ix_guests_phone'), 'guests', ['phone'], unique=True)
    op.create_index(op.f('ix_guests_qr_code'), 'guests', ['qr_code'], unique=True)
    op.create_index(op.f('ix_guests_qr_token'), 'guests', ['qr_token'], unique=True)
    op.create_index(op.f('ix_guests_rsvp_status'), 'guests', ['rsvp_status'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_tokens_status'), 'user_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_user_tokens_token'), 'user_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_guest_id'), 'tokens', ['guest_id'], unique=False)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_status'), 'tokens', ['status'], unique=False)
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_status'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_guest_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_token'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_status'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_guests_rsvp_status'), table_name='guests')
    op.drop_index(op.f('ix_guests_qr_token'), table_name='guests')
    op.drop_index(op.f('ix_guests_qr_code'), table_name='guests')
    op.drop_index(op.f('ix_guests_phone'), table_name='guests')
    op.drop_index(op.f('ix_guests_organization'), table_name='guests')
    op.drop_index(op.f('ix_guests_is_vip'), table_name='guests')
    op.drop_index(op.f('ix_guests_invitation_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_group_tag'), table_name='guests')
    op.drop_index(op.f('ix_guests_full_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_event_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_index(op.f('ix_guests_checkin_at'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_events_start_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
